[package]
name = "caring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = {version = "4.1.1", features = ["group"]}
derive_more = "0.99.17"
ff = { version = "0.13.0", features = ["derive"] }
fixed = "2.0.0-alpha.11"
gf256 = "0.3.0"
group = "0.13.0"
num-traits = "0.2.16"
rand = "0.8.5"
