name: "PyO3 CI"
on:
  workflow_run:
    workflows: ["Test Suite"]
    types: [completed]
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, aarch64, armv7l]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install C compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install Zigbuild
        run: pip install cargo-zigbuild
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --zig
          sccache: 'true'
          container: 'off'
          working-directory: pycare
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: pycare/dist

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install C compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Zigbuild
        run: pip install cargo-zigbuild
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: i686-pc-windows-msvc
          args: --release --out dist --zig
          sccache: 'true'
          container: 'off'
          working-directory: pycare
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: pycare/dist

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install C compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Zigbuild
        run: pip install cargo-zigbuild
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --zig
          sccache: 'true'
          container: 'off'
          working-directory: pycare
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: pycare/dist

